[tools]
go = "1.24.0"
lefthook = "1.11.2"

[task_config]
includes = ["fxmap/.tasks.toml"]

[tasks.tidy]
description = "Tidy go modules"
depends = ["tidy:*"]

[tasks.vet]
description = "Run go vet"
depends = ["vet:*"]

[tasks.benchmark]
description = "Run benchmarks for all libraries"
run = "go test ./maps/... -bench . -test.benchmem"
